//HOME PAGE - required the inclusion of variables so the string htmlPage4 is returned and this is run as the HTML
namespace home {
  String runPage(String petName){
    String htmlPage4 = "";
    htmlPage4 += "<html>";
    htmlPage4 += "<head>";
    htmlPage4 += "<meta http-equiv=\"content-type\" content=\"text/html;charset=UTF-8\">";
    htmlPage4 += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
    htmlPage4 += "<title>Home</title>";
    htmlPage4 += "<style>";
    htmlPage4 += "html {";
    htmlPage4 += "height: 100%;";
    htmlPage4 += "width: 100%;";
    htmlPage4 += "}";
    htmlPage4 += "html {";
    htmlPage4 += "font-family: Helvetica;";
    htmlPage4 += "background-color: #76a2ea;";
    htmlPage4 += "display: inline-block;";
    htmlPage4 += "margin: 0px auto;";
    htmlPage4 += "text-align: center;";
    htmlPage4 += "}";
    htmlPage4 += "h1 {";
    htmlPage4 += "font-size: 64px;";
    htmlPage4 += "}";
    htmlPage4 += "body {";
    htmlPage4 += "color:white;";
    htmlPage4 += "}";
    htmlPage4 += "button {";
    htmlPage4 += "background-color: #4caeac;";
    htmlPage4 += "border: none;";
    htmlPage4 += "color: white;";
    htmlPage4 += "padding: 16px 40px;";
    htmlPage4 += "border-radius: 10px;";
    htmlPage4 += "text-decoration: none;";
    htmlPage4 += "font-size: 30px;";
    htmlPage4 += "margin: 6px;";
    htmlPage4 += "cursor: pointer;}";
    htmlPage4 += "a {";
    htmlPage4 += "text-decoration: none;";
    htmlPage4 += "color: white;";
    htmlPage4 += "}";
    htmlPage4 += "form {";
    htmlPage4 += "margin: 10px;";
    htmlPage4 += "text-align: left;";
    htmlPage4 += "font-size: 20px;";
    htmlPage4 += "}";
    htmlPage4 += ".textBox {";
    htmlPage4 += "padding: 5px;";
    htmlPage4 += "margin: 10px;";
    htmlPage4 += "}";
    htmlPage4 += ".submit {";
    htmlPage4 += "margin: 20px;";
    htmlPage4 += "border: black 1px;";
    htmlPage4 += "border-radius: 10%;";
    htmlPage4 += "padding: 5px;";
    htmlPage4 += "font-size: 24px;";
    htmlPage4 += "}";
    htmlPage4 += "</style>";
    htmlPage4 += "</head>";
    htmlPage4 += "<body>";
    htmlPage4 += "<h1>"+petName+"'s Home</h1>";
    htmlPage4 += "<button><a href=\"/meditate\">Sleep</a></button><br>";
    htmlPage4 += "<button><a href=\"/play\">Play</a></button><br>";
    htmlPage4 += "<button><a href=\"/study\">Study</a></button><br>";
    htmlPage4 += "<button><a href=\"/stats\">Stats</a></button><br>";
    htmlPage4 += "<button><a href=\"/\">Log Out</a></button>";
    htmlPage4 += "</body>";
    htmlPage4 += "</html>";
//)=====";
return htmlPage4;
  }
}